sudo: required

language: ruby
cache: bundler

services:
- docker

before_install:
- docker build -t centralmarinsoccer/web .

after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push centralmarinsoccer/web;
    fi

env:
  matrix:
  - DOCKER_FILE=Dockerfile
  global:
  - CI_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - CI_REGISTRY_IMAGE=$TRAVIS_REPO_SLUG
