version: '2'
services:
  db:
    image: mysql
    env_file: .env
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - 3306:3306
  app:
    build: .
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- /app/bin/rails s -b 0.0.0.0 -p 3000 -e development"
    volumes:
      - .:/app
      - ./assets/ckeditor_assets:/app/public/ckeditor_assets
      - ./assets/uploads:/app/public/uploads
    ports:
      - "3000:3000"
      - "1234:1234"
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
     - DOMAIN=centralmarinsoccer.local
    ports:
     - "8080:80"
volumes:
  mysql:
