version: '2'
services:
  db:
    image: mysql
    env_file:
     - .centralmarinsoccer.env
    volumes:
     - mysql:/var/lib/mysql
     - ./data:/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
  app:
     image: centralmarinsoccer/web
     env_file:
      - .centralmarinsoccer.env
     environment:
      - RAILS_ENV=development
     command: bundle exec rails s -p 8000 -b '0.0.0.0'
     volumes:
      - .:/myapp
      - ./config/CentralMarinSoccerTryouts.p12:/myapp/config/CentralMarinSoccerTryouts.p12
      - ./tmp/ckeditor_assets:/myapp/public/ckeditor_assets
      - ./tmp/uploads:/myapp/public/uploads
     ports:
      - "8000:8000"
     depends_on:
       - db
#  web:
#    image: centralmarinsoccer/caddy
#    volumes:
#      - ./caddy/Caddyfile:/etc/Caddyfile
#      - ./tmp/uploads:/myapp/public/uploads
#      - ./tmp/ckeditor_assets:/myapp/public/ckeditor_assets
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes_from:
#      - app
#    depends_on:
#      - app
volumes:
  mysql:

