version: '2'
services:
  db:
    image: mysql
    env_file: .centralmarin.env
    volumes:
    - mysql:/var/lib/mysql
    - ./tools:/tools
    ports:
    - "3306:3306"
  app:
    build:
      context: .
      dockerfile: passenger/Dockerfile
    image: centralmarin/app
    env_file: .centralmarin.env
    depends_on:
      - db
    volumes:
      - .:/app
      - assets:/app/public
    ports:
      - "3000:3000"
  web:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    image: centralmarin/web
    depends_on:
      - app
    env_file: .centralmarin.env
    volumes:
      - ./caddy/Caddyfile.localhost:/etc/Caddyfile
      - assets:/app/public
    ports:
     - "8000:8000"
volumes:
  mysql:
  assets:
