version: '2'
services:
  db:
    image: mysql
    env_file:
     - .centralmarinsoccer.env
    volumes:
     - mysql:/var/lib/mysql
     - ./data:/docker-entrypoint-initdb.d
     - .:/opt
    ports:
     - "3306:3306"
  app:
     build: .
     command: bundle exec unicorn -c config/unicorn.rb
     env_file:
      - .centralmarinsoccer.env
     volumes:
#      - .:/myapp
      - ./tmp/ckeditor_assets:/myapp/public/ckeditor_assets
      - ./tmp/uploads:/myapp/public/uploads
     ports:
      - "8000:8000"
     depends_on:
       - db
  web:
    #image: abiosoft/caddy
    build: caddy
    ports: 
      - "80:80"
    volumes_from:
      - app
    depends_on:
      - app
volumes:
  mysql:

