version: '2'
services:
  db:
    image: mysql
    env_file: .env
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - 3306:3306
  app:
    build: .
    depends_on:
      - db
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ckeditor_assets:/myapp/public/ckeditor_assets
      - uploads:/myapp/public/uploads
    ports:
      - "3000:3000"
volumes:
  mysql:
  uploads:
  ckeditor_assets: