version: '2'
services:
  app:
    command: bash -c "rm -rf tmp/pids && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- /app/bin/rails s -b 0.0.0.0 -p 3000 -e development"
    ports:
      - "3000:3000"
      - "1234:1234"

