version: '2'
services:
  db:
    image: mysql
    env_file: .env
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - 3306:3306
#  web:
#    build: .
#    volumes:
#      - .:/myapp
#      - ./docker/public/ckeditor_assets:/myapp/public/ckeditor_assets
#      - ./docker/public/uploads:/myapp/public/uploads
#    ports:
#      - "3000:3000"
#    links:
#      - db:DBHOST
#    env_file:
#      - '.env.web'
volumes:
  mysql: