development: &DEVELOPMENT
  switch_hosts: { es: "centralmarinsoccer.local", en: "es.centralmarinsoccer.local" }
test:
  <<: *DEVELOPMENT

production:
  switch_hosts: { es: "centralmarinsoccer.com", en: "es.centralmarinsoccer.com" }
