development: &DEVELOPMENT
  switch_hosts: { es: "localhost", en: "es.localhost" }
test:
  <<: *DEVELOPMENT
staging:
  switch_hosts: { es: "staging.centralmarinsoccer.com", en: "es.staging.centralmarinsoccer.com" }

production:
  switch_hosts: { es: "centralmarinsoccer.com", en: "es.centralmarinsoccer.com" }
