<Environment>:
  mailer_host: 'XXXXXXXXXXXXXXX'
  secret_key_base: 'XXXXXXXXXXXXXXX'
  smtp_username: 'XXXXXXX@XXXXXXXXXXXXXXX'
  smtp_password: 'XXXXXXXXXXXXXXX'
  default_user: 'XXXXXXXXXXXXXXX@XXXXXXXXXXXXXXX'
  teamsnap_token: 'XXXXXXXXXXXXXXX'
  server_user: 'XXXXXXXXXXXXXXX'
