
common: &common
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  google_service_account_id: <%= ENV['GOOGLE_SERVICE_ACCOUNT_ID'] %>
  google_key_file: <%= ENV['GOOGLE_KEY_FILE'] %>
  google_key_secret: <%= ENV['GOOGLE_KEY_SECRET'] %>
  google_drive_account: <%= ENV['GOOGLE_DRIVE_ACCOUNT'] %>
  google_email_app_pwd: <%= ENV['GOOGLE_EMAIL_APP_PWD'] %>
  google_email_from: <%= ENV['GOOGLE_EMAIL_FROM'] %>
  google_info_email_from: <%= ENV['GOOGLE_INFO_EMAIL_FROM'] %>
  bing_client_id: <%= ENV['BING_CLIENT_ID'] %>
  bing_client_secret: <%= ENV['BING_CLIENT_SECRET'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_domain: <%= ENV['MAILGUN_DOMAIN'] %>
  mailgun_from: <%= ENV['MAILGUN_FROM'] %>
  teamsnap_token: <%= ENV['TEAMSNAP_TOKEN'] %>
  stripe_secret: <%= ENV['STRIPE_SECRET'] %>
  stripe_key: <%= ENV['STRIPE_KEY'] %>

development:
  <<: *common
  mailer_host: 'localhost:3000'
  google_drive_tryouts_doc: 'Tryout Registration - development'

production:
  <<: *common
  mailer_host: 'centralmarinsoccer.com'
  google_drive_tryouts_doc: 'Tryout Registration'
